import 'package:flutter/material.dart';
import './recipe_detail.dart';
import './recipe_search.dart';

class Recipe {
  late int servings;
  late List<Ingredient> ingredient;
  late String label;
  late String imageUrl;
  late List<String> procedures;
  late String category;

  Recipe(this.label, this.imageUrl, this.servings, this.ingredient,
      this.procedures, this.category);
}

class Ingredient {
  late double quantity;
  late String measure;
  late String name;

  Ingredient(this.quantity, this.measure, this.name);
}

List<Recipe> samples = [
  Recipe(
    'Avocado Toast',
    'assets/Avocado Toast.jpg',
    1,
    [
      Ingredient(1, 'ripe', 'Avocado'),
      Ingredient(2, 'slices', 'Bread (e.g., whole grain, sourdough)'),
      Ingredient(1, 'tablespoon', 'Lemon juice'),
      Ingredient(1 / 4, 'teaspoon', 'Salt'),
      Ingredient(1 / 8, 'teaspoon', 'Black pepper'),
      Ingredient(1 / 4, 'teaspoon', 'Red pepper flakes (optional)'),
      Ingredient(1, 'tablespoon', 'Extra virgin olive oil'),
      Ingredient(1, 'clove', 'Garlic (optional, for rubbing on toast)'),
      Ingredient(
          1, 'tablespoon', 'Fresh herbs (e.g., cilantro, parsley, chives)'),
    ],
    [
      '1. Cut the avocado in half, remove the pit, and scoop out the flesh into a bowl.',
      '2. Mash the avocado with a fork until it reaches your desired consistency.',
      '3. Stir in lemon juice, salt, black pepper, and red pepper flakes if using.',
      '4. Toast the bread slices until golden brown and crispy.',
      '5. Optional: Rub the toasted bread with a clove of garlic for extra flavor.',
      '6. Spread the mashed avocado mixture evenly onto the toasted bread slices.',
      '7. Drizzle extra virgin olive oil over the avocado mixture.',
      '8. Garnish with fresh herbs of your choice.',
      '9. Serve immediately and enjoy!',
    ],
    'Breakfast',
  ),
  Recipe(
    'Spaghetti and Meatballs',
    'assets/spaghetti.jpg',
    4,
    [
      Ingredient(1, 'box', 'Spaghetti'),
      Ingredient(4, '', 'Frozen Meatballs'),
      Ingredient(0.5, 'jar', 'Marinara sauce'),
      Ingredient(1, 'tablespoon', 'Olive oil'),
      Ingredient(2, 'cloves', 'Garlic'),
      Ingredient(1 / 4, 'cup', 'Onion'),
      Ingredient(1 / 4, 'cup', 'Bell peppers (mixed)'),
      Ingredient(1 / 4, 'cup', 'Mushrooms'),
      Ingredient(1, 'can', 'Crushed tomatoes'),
      Ingredient(1, 'teaspoon', 'Italian seasoning'),
      Ingredient(1 / 4, 'cup', 'Fresh basil'),
      Ingredient(1 / 4, 'cup', 'Fresh parsley'),
      Ingredient(1 / 2, 'cup', 'Parmesan cheese (grated)'),
      Ingredient(1 / 4, 'cup', 'Mozzarella cheese (shredded)'),
    ],
    [
      '1. Boil spaghetti and cook until al dente. Drain.',
      '2. Heat olive oil in a skillet. Sauté garlic, onion, bell peppers, and mushrooms until soft.',
      '3. Add crushed tomatoes and Italian seasoning. Simmer for 10 minutes.',
      '4. Heat meatballs in marinara sauce according to package instructions.',
      '5. Combine spaghetti with sauce and meatballs.',
      '6. Serve topped with Parmesan and mozzarella cheese.',
    ],
    'Dinner',
  ),
  Recipe(
    'Dosa',
    'assets/Dosa.jpg',
    4,
    [
      Ingredient(2, 'cups', 'Rice (preferably parboiled rice)'),
      Ingredient(1 / 2, 'cup', 'Split black lentils (urad dal)'),
      Ingredient(1 / 4, 'teaspoon', 'Fenugreek seeds'),
      Ingredient(1, 'teaspoon', 'Salt'),
      Ingredient(1 / 4, 'cup',
          'Vegetable oil or ghee (clarified butter), for cooking'),
    ],
    [
      '1. Rinse the rice and split black lentils separately under cold water until the water runs clear.',
      '2. In a large bowl, soak the rice, split black lentils, and fenugreek seeds in enough water to cover them completely. Let them soak for at least 4 hours or overnight.',
      '3. After soaking, drain the water from the rice and lentils. Transfer them to a blender or wet grinder.',
      '4. Add salt and enough water to the blender to make a smooth batter. The consistency should be similar to pancake batter.',
      '5. Transfer the batter to a large bowl and cover it. Let it ferment in a warm place for 8-12 hours or overnight. The batter should rise and become slightly airy.',
      '6. After fermentation, stir the batter gently. If its too thick, you can add a little water to adjust the consistency.',
      '7. Heat a non-stick skillet or dosa pan over medium heat. Once hot, lightly grease it with oil or ghee.',
      '8. Pour a ladleful of batter onto the center of the skillet and spread it in a circular motion to form a thin, even layer. The dosa should be about 8-10 inches in diameter.',
      '9. Drizzle a little oil or ghee around the edges of the dosa and cook until the bottom turns golden brown and crispy.',
      '10. Flip the dosa using a spatula and cook the other side for a minute or until its lightly browned.',
      '11. Remove the dosa from the skillet and serve hot with chutney, sambar, or any desired filling.',
      '12. Repeat the process with the remaining batter, greasing the skillet as needed.',
    ],
    'Breakfast',
  ),
  Recipe(
    'Butter Chicken',
    'assets/Butter Chicken.jpg',
    4,
    [
      Ingredient(1, 'lb',
          'Boneless, skinless chicken thighs or breasts, cut into bite-sized pieces'),
      Ingredient(1 / 2, 'cup', 'Yogurt'),
      Ingredient(2, 'tablespoons', 'Lemon juice'),
      Ingredient(1, 'tablespoon', 'Ginger paste'),
      Ingredient(1, 'tablespoon', 'Garlic paste'),
      Ingredient(2, 'teaspoons', 'Garam masala'),
      Ingredient(2, 'teaspoons', 'Ground coriander'),
      Ingredient(1 / 2, 'teaspoon', 'Ground turmeric'),
      Ingredient(1 / 2, 'teaspoon', 'Cayenne pepper (adjust to taste)'),
      Ingredient(1, 'teaspoon', 'Salt'),
      Ingredient(1 / 4, 'cup', 'Butter'),
      Ingredient(1, 'large', 'Onion, finely chopped'),
      Ingredient(2, 'cups', 'Tomato puree'),
      Ingredient(1 / 4, 'cup', 'Heavy cream'),
      Ingredient(1, 'teaspoon', 'Sugar'),
      Ingredient(1 / 4, 'cup', 'Fresh cilantro leaves, chopped (for garnish)'),
    ],
    [
      '1. In a large bowl, combine yogurt, lemon juice, ginger paste, garlic paste, garam masala, ground coriander, ground turmeric, cayenne pepper, and salt. Mix well.',
      '2. Add the chicken pieces to the marinade and toss until evenly coated. Cover and refrigerate for at least 1 hour, or overnight for best results.',
      '3. In a large skillet or pot, melt the butter over medium heat. Add the chopped onion and sauté until soft and translucent, about 5 minutes.',
      '4. Add the marinated chicken to the skillet, along with any excess marinade. Cook, stirring occasionally, until the chicken is browned on all sides, about 8-10 minutes.',
      '5. Stir in the tomato puree and sugar. Reduce heat to low, cover, and simmer for 15-20 minutes, stirring occasionally, until the chicken is cooked through and the sauce has thickened.',
      '6. Stir in the heavy cream and simmer for an additional 5 minutes.',
      '7. Taste and adjust seasoning if needed.',
      '8. Garnish with chopped cilantro leaves before serving.',
      '9. Serve hot with rice, naan, or roti.',
    ],
    'Dinner',
  ),
  Recipe(
    'Paneer Paratha',
    'assets/Paneer Paratha.jpg',
    4,
    [
      Ingredient(2, 'cups', 'Whole wheat flour (atta)'),
      Ingredient(1, 'cup', 'Paneer, grated'),
      Ingredient(1, 'medium', 'Onion, finely chopped'),
      Ingredient(2, 'green chilies', 'Green chilies, finely chopped'),
      Ingredient(2, 'tablespoons', 'Fresh coriander leaves, chopped'),
      Ingredient(1 / 2, 'teaspoon', 'Cumin seeds'),
      Ingredient(1 / 2, 'teaspoon', 'Turmeric powder'),
      Ingredient(1 / 2, 'teaspoon', 'Garam masala'),
      Ingredient(1 / 2, 'teaspoon', 'Salt'),
      Ingredient(1, 'tablespoon', 'Oil, for cooking'),
      Ingredient(1 / 4, 'cup', 'Water (as needed)'),
    ],
    [
      '1. In a large mixing bowl, combine whole wheat flour, grated paneer, chopped onion, chopped green chilies, chopped coriander leaves, cumin seeds, turmeric powder, garam masala, and salt.',
      '2. Knead the mixture into a smooth dough, adding water as needed to bind everything together. The dough should be soft and pliable.',
      '3. Divide the dough into equal-sized balls, about the size of a golf ball.',
      '4. Take one dough ball and flatten it slightly with your palms. Dust it with some flour and roll it out into a circle, about 6-7 inches in diameter.',
      '5. Heat a tawa (griddle) or a non-stick skillet over medium heat. Place the rolled-out dough circle onto the hot tawa.',
      '6. Cook for about a minute until small bubbles start to appear on the surface.',
      '7. Flip the paratha and drizzle a little oil around the edges. Press down gently with a spatula and cook until golden brown spots appear on both sides.',
      '8. Remove the cooked paratha from the tawa and place it on a plate. Repeat the process with the remaining dough balls.',
      '9. Serve hot with yogurt, pickle, or your favorite chutney.',
    ],
    'Lunch',
  ),
  Recipe(
    'Rajma Chawal',
    'assets/Rajma Chaval.jpg',
    4,
    [
      Ingredient(1, 'cup', 'Rajma (red kidney beans)'),
      Ingredient(1, 'cup', 'Basmati rice'),
      Ingredient(1, 'medium', 'Onion, finely chopped'),
      Ingredient(2, 'medium', 'Tomatoes, finely chopped'),
      Ingredient(2, 'cloves', 'Garlic, minced'),
      Ingredient(1, 'Ginger', 'grated'),
      Ingredient(2, 'green chilies', 'Green chilies, slit lengthwise'),
      Ingredient(1, 'teaspoon', 'Cumin seeds'),
      Ingredient(1, 'teaspoon', 'Turmeric powder'),
      Ingredient(1, 'tablespoon', 'Coriander powder'),
      Ingredient(1 / 2, 'teaspoon', 'Red chili powder (adjust to taste)'),
      Ingredient(1, 'teaspoon', 'Garam masala'),
      Ingredient(1 / 4, 'cup', 'Fresh cilantro leaves, chopped'),
      Ingredient(2, 'tablespoons', 'Cooking oil'),
      Ingredient(2, 'cups', 'Water'),
      Ingredient(1, 'tablespoon', 'Ghee (optional, for serving)'),
      Ingredient(1, 'teaspoon',
          'Kasuri methi (dried fenugreek leaves, optional, for garnish)'),
      Ingredient(1, 'teaspoon', 'Lemon juice (optional, for serving)'),
      Ingredient(1, 'tablespoon', 'Fresh cream (optional, for serving)'),
    ],
    [
      '1. Rinse the rajma under cold water and soak them in enough water overnight or for at least 8 hours. Drain and set aside.',
      '2. In a pressure cooker or a large pot, heat cooking oil over medium heat. Add cumin seeds and let them splutter.',
      '3. Add chopped onions and sauté until they turn translucent, about 3-4 minutes.',
      '4. Add minced garlic, grated ginger, and slit green chilies. Sauté for another 2 minutes.',
      '5. Stir in chopped tomatoes and cook until they soften and the oil starts to separate, about 5-6 minutes.',
      '6. Add turmeric powder, coriander powder, red chili powder, and garam masala. Mix well and cook for 2 minutes.',
      '7. Add soaked and drained rajma to the pot. Stir to combine with the masala mixture.',
      '8. Pour in water and season with salt. Stir well.',
      '9. If using a pressure cooker, close the lid and cook the rajma over medium heat for about 15-20 minutes, or until they are soft and tender. If using a regular pot, cover and cook over low heat for about 1.5 to 2 hours, or until the rajma is soft and cooked through. You may need to add more water if necessary.',
      '10. Once the rajma is cooked, mash some of the beans with the back of a spoon to thicken the gravy. Adjust salt and spices to taste.',
      '11. Garnish with chopped cilantro leaves and kasuri methi (if using).',
      '12. Serve hot with steamed basmati rice, drizzled with ghee, and a squeeze of lemon juice. Optionally, serve with a dollop of fresh cream on top.',
    ],
    'Lunch',
  ),
  Recipe(
    'Pav Bhaji',
    'assets/Pav Bhaji.jpg',
    4,
    [
      Ingredient(4, 'medium', 'Potatoes, boiled and mashed'),
      Ingredient(2, 'medium', 'Tomatoes, finely chopped'),
      Ingredient(1, 'cup',
          'Mixed vegetables (such as peas, carrots, cauliflower, bell peppers), finely chopped'),
      Ingredient(1, 'large', 'Onion, finely chopped'),
      Ingredient(1 / 2, 'cup', 'Capsicum (green bell pepper), finely chopped'),
      Ingredient(2, 'tablespoons', 'Butter'),
      Ingredient(2, 'tablespoons', 'Pav Bhaji masala'),
      Ingredient(1, 'teaspoon', 'Cumin seeds'),
      Ingredient(1, 'tablespoon', 'Ginger-garlic paste'),
      Ingredient(2, 'green chilies', 'Green chilies, finely chopped'),
      Ingredient(1, 'teaspoon', 'Red chili powder'),
      Ingredient(1 / 2, 'teaspoon', 'Turmeric powder'),
      Ingredient(1, 'teaspoon', 'Salt (or to taste)'),
      Ingredient(1 / 4, 'cup', 'Fresh coriander leaves, chopped'),
      Ingredient(1, 'tablespoon', 'Lemon juice'),
      Ingredient(8, 'Pav Indian bread', 'rolls'),
      Ingredient(1, 'tablespoon', 'Oil (for toasting pav)'),
      Ingredient(1, 'tablespoon', 'Butter (for serving)'),
      Ingredient(1, 'small', 'Onion, finely chopped (for garnish)'),
      Ingredient(1, 'small', 'Lemon, cut into wedges (for serving)'),
    ],
    [
      '1. Heat butter in a large pan or kadai over medium heat. Add cumin seeds and let them splutter.',
      '2. Add chopped onions and sauté until they turn translucent.',
      '3. Add ginger-garlic paste and chopped green chilies. Sauté for a minute until the raw smell disappears.',
      '4. Add chopped capsicum and mixed vegetables. Cook until they are slightly softened.',
      '5. Add chopped tomatoes and cook until they become mushy and the oil starts to separate from the mixture.',
      '6. Add pav bhaji masala, red chili powder, turmeric powder, and salt. Mix well.',
      '7. Add the mashed potatoes and mix until everything is well combined.',
      '8. Mash the mixture using a potato masher or the back of a spoon. Add water as needed to achieve the desired consistency. Simmer for 10-12 minutes, stirring occasionally.',
      '9. Add chopped coriander leaves and lemon juice. Mix well and cook for another 2 minutes.',
      '10. Heat a griddle or tawa over medium heat. Slice the pav horizontally into halves.',
      '11. Spread a little butter on the inner sides of the pav and toast them on the griddle until they are golden brown and crisp.',
      '12. Serve the hot pav bhaji with a dollop of butter on top, garnished with finely chopped onions and lemon wedges on the side.',
      '13. Enjoy the delicious pav bhaji with your family and friends!',
    ],
    'Lunch',
  ),
  Recipe(
    'Chicken Biryani',
    'assets/Biryani.jpg',
    6,
    [
      Ingredient(2, 'cups', 'Basmati rice'),
      Ingredient(1, 'lb',
          'Chicken (bone-in pieces, preferably thighs and drumsticks)'),
      Ingredient(1 / 2, 'cup', 'Yogurt'),
      Ingredient(2, 'tablespoons', 'Ginger paste'),
      Ingredient(2, 'tablespoons', 'Garlic paste'),
      Ingredient(1, 'large', 'Onion, thinly sliced'),
      Ingredient(2, 'large', 'Tomatoes, chopped'),
      Ingredient(2, 'tablespoons', 'Biryani masala'),
      Ingredient(1, 'teaspoon', 'Turmeric powder'),
      Ingredient(1, 'teaspoon', 'Red chili powder'),
      Ingredient(1 / 2, 'teaspoon', 'Ground cumin'),
      Ingredient(1 / 2, 'teaspoon', 'Ground coriander'),
      Ingredient(1 / 4, 'teaspoon', 'Ground cardamom'),
      Ingredient(1 / 4, 'cup', 'Fresh cilantro leaves, chopped'),
      Ingredient(1 / 4, 'cup', 'Fresh mint leaves, chopped'),
      Ingredient(1 / 2, 'cup', 'Fried onions (store-bought or homemade)'),
      Ingredient(1 / 4, 'cup', 'Ghee (clarified butter)'),
      Ingredient(1 / 4, 'cup', 'Warm milk'),
      Ingredient(1 / 4, 'teaspoon', 'Saffron threads'),
      Ingredient(1 / 4, 'cup', 'Cashews, fried (optional, for garnish)'),
      Ingredient(1 / 4, 'cup', 'Raisins, fried (optional, for garnish)'),
    ],
    [
      '1. Rinse the basmati rice under cold water until the water runs clear. Soak the rice in enough water to cover it completely for 30 minutes. Drain and set aside.',
      '2. In a large bowl, combine yogurt, ginger paste, garlic paste, biryani masala, turmeric powder, red chili powder, ground cumin, ground coriander, ground cardamom, chopped cilantro leaves, and chopped mint leaves. Mix well to form a marinade.',
      '3. Add the chicken pieces to the marinade and toss until evenly coated. Cover and refrigerate for at least 1 hour, or overnight for best results.',
      '4. In a large pot or Dutch oven, heat ghee over medium heat. Add the sliced onions and cook until golden brown and caramelized, about 10-12 minutes.',
      '5. Add the marinated chicken to the pot, along with any excess marinade. Cook, stirring occasionally, until the chicken is browned on all sides, about 8-10 minutes.',
      '6. Stir in the chopped tomatoes and cook until they break down and form a thick gravy, about 5-7 minutes.',
      '7. In a separate small bowl, soak saffron threads in warm milk for 5 minutes.',
      '8. Preheat the oven to 350°F (175°C).',
      '9. In a large oven-safe dish, layer half of the soaked basmati rice evenly at the bottom. Top with the cooked chicken mixture, spreading it out evenly.',
      '10. Layer the remaining rice on top of the chicken mixture.',
      '11. Drizzle the saffron-infused milk over the rice and sprinkle fried onions on top.',
      '12. Cover the dish tightly with aluminum foil and bake in the preheated oven for 30-35 minutes, until the rice is fully cooked and fluffy.',
      '13. Garnish with fried cashews and raisins, if desired, before serving.',
      '14. Serve hot with raita (yogurt dip) or your favorite side salad.',
    ],
    'Dinner',
  ),
  Recipe(
    'Tomato Soup',
    'assets/Tomato soup.jpg',
    2,
    [
      Ingredient(4, 'large', 'Tomatoes'),
      Ingredient(1, 'tablespoon', 'Olive oil'),
      Ingredient(2, 'cloves', 'Garlic'),
      Ingredient(1, 'cup', 'Vegetable broth'),
      Ingredient(1 / 4, 'cup', 'Heavy cream'),
      Ingredient(1, 'teaspoon', 'Sugar'),
      Ingredient(1 / 2, 'teaspoon', 'Salt'),
      Ingredient(1 / 4, 'teaspoon', 'Black pepper'),
      Ingredient(1, 'tablespoon', 'Basil (chopped)'),
      Ingredient(1, 'tablespoon', 'Parsley (chopped)'),
    ],
    [
      '1. Preheat the oven to 400°F (200°C).',
      '2. Cut the tomatoes in half and place them on a baking sheet.',
      '3. Drizzle olive oil over the tomatoes and season with salt and pepper.',
      '4. Roast the tomatoes in the oven for 25-30 minutes until soft and caramelized.',
      '5. Heat olive oil in a large pot over medium heat. Add minced garlic and cook until fragrant.',
      '6. Add roasted tomatoes to the pot along with vegetable broth, sugar, salt, and pepper. Bring to a simmer.',
      '7. Use an immersion blender to puree the soup until smooth.',
      '8. Stir in heavy cream and chopped basil. Simmer for another 5 minutes.',
      '9. Adjust seasoning if necessary.',
      '10. Serve hot, garnished with chopped parsley.',
    ],
    'Lunch',
  ),
  Recipe(
    'Grilled Cheese Sandwich',
    'assets/Grilled sandwich.jpg',
    1,
    [
      Ingredient(2, 'slices', 'Cheese'),
      Ingredient(2, 'slices', 'Bread'),
      Ingredient(1, 'tablespoon', 'Butter'),
    ],
    [
      '1. Spread butter on one side of each bread slice.',
      '2. Place one slice of cheese on the unbuttered side of a bread slice.',
      '3. Top with the other bread slice, buttered side facing out.',
      '4. Heat a skillet over medium heat.',
      '5. Place the sandwich in the skillet and cook until golden brown on one side, about 3-4 minutes.',
      '6. Flip the sandwich and cook until the other side is golden brown and the cheese is melted, about 3-4 minutes more.',
      '7. Remove from the skillet and let cool slightly before serving.',
    ],
    'Lunch',
  ),
  Recipe(
    'Chocolate Chip Cookies',
    'assets/Cookie.jpg',
    24,
    [
      Ingredient(4, 'cups', 'flour'),
      Ingredient(2, 'cups', 'sugar'),
      Ingredient(0.5, 'cups', 'chocolate chips'),
      Ingredient(2, 'large', 'eggs'),
      Ingredient(1, 'teaspoon', 'vanilla extract'),
      Ingredient(1, 'teaspoon', 'baking soda'),
      Ingredient(0.5, 'teaspoon', 'salt'),
      Ingredient(1, 'cup', 'butter (softened)'),
      Ingredient(1, 'cup', 'packed brown sugar')
    ],
    [
      '1. Preheat oven to 375 degrees F (190 degrees C).',
      '2. Cream together the butter and sugars until light and fluffy.',
      '3. Beat in eggs one at a time, then stir in the vanilla.',
      '4. Combine flour, baking soda, and salt. Add to the wet ingredients and mix until just combined.',
      '5. Fold in chocolate chips.',
      '6. Drop by rounded tablespoons onto ungreased baking sheets.',
      '7. Bake for 10-12 minutes or until golden brown.'
    ],
    'Lunch',
  ),
  Recipe(
    'Taco Salad',
    'assets/taco salad.jpg',
    1,
    [
      Ingredient(4, 'ounces', 'nachos'),
      Ingredient(3, 'ounces', 'taco meat'),
      Ingredient(1, 'cup', 'shredded cheese'),
      Ingredient(1 / 4, 'cup', 'chopped tomatoes'),
      Ingredient(1 / 4, 'cup', 'chopped lettuce'),
      Ingredient(1 / 4, 'cup', 'salsa'),
      Ingredient(1 / 4, 'cup', 'sour cream'), // Optional
    ],
    [
      '1. Brown the taco meat in a skillet over medium heat until fully cooked. Drain any excess grease.',
      '2. On a serving plate, arrange a bed of crushed nachos as the base.',
      '3. Layer the nachos with the cooked taco meat.',
      '4. Sprinkle shredded cheese over the meat layer.',
      '5. Add chopped tomatoes and lettuce as the next layer.',
      '6. Drizzle salsa evenly over the salad.',
      '7. Optionally, garnish with a dollop of sour cream.',
      '8. Serve immediately and enjoy!'
    ],
    'Dinner',
  ),
  Recipe(
    'Hawaiian Pizza',
    'assets/Hawaiian pizza.jpg',
    4,
    [
      Ingredient(1, 'item',
          'pre-made pizza crust'), // Or add ingredients for homemade dough
      Ingredient(1, 'cup', 'pineapple chunks'),
      Ingredient(8, 'oz', 'ham'),
      Ingredient(1, 'cup', 'shredded mozzarella cheese'),
      Ingredient(0.5, 'cup', 'pizza sauce')
    ],
    [
      'Preheat oven according to pizza crust instructions.',
      'Spread pizza sauce on the crust.',
      'Top with cheese, ham, and pineapple.',
      'Bake according to pizza crust instructions.'
    ],
    'Dinner',
  ),
  Recipe(
    'Omelette',
    'assets/Omlette.jpg',
    1,
    [
      Ingredient(2, 'large', 'Eggs'),
      Ingredient(2, 'tablespoons', 'Milk'),
      Ingredient(1 / 4, 'cup', 'Shredded cheese (e.g., cheddar, mozzarella)'),
      Ingredient(1 / 4, 'cup',
          'Diced vegetables (e.g., bell peppers, onions, mushrooms)'),
      Ingredient(1 / 4, 'teaspoon', 'Salt'),
      Ingredient(1 / 8, 'teaspoon', 'Black pepper'),
      Ingredient(1, 'tablespoon', 'Butter or oil'),
    ],
    [
      '1. In a bowl, beat the eggs with milk until well combined. Season with salt and pepper.',
      '2. Heat butter or oil in a skillet over medium heat.',
      '3. Pour the egg mixture into the skillet and let it cook for a minute until the edges start to set.',
      '4. Sprinkle shredded cheese and diced vegetables evenly over one half of the omelette.',
      '5. Using a spatula, carefully fold the other half of the omelette over the filling.',
      '6. Cook for another 2-3 minutes until the cheese is melted and the omelette is cooked through.',
      '7. Slide the omelette onto a plate and serve hot.',
    ],
    'Breakfast',
  ),
];
